adminPassword: admin123

service:
  type: ClusterIP
  port: 3000

persistence:
  enabled: false
  size: 1Gi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server
        access: proxy
        isDefault: true
