prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "-"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
