apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: 80
      targetPort: 3000  # or 8080 for backend
