apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/gitops-react-java-app
    targetRevision: HEAD
    path: helm/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
