replicaCount: 2

namespace: backend

image:
  repository: kemiagbabiaka/java-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: backend.example.com
  path: /