replicaCount: 1

image:
  repository: kemiagbabiaka/java-backend
  tag: latest
  pullPolicy: IfNotPresent
  args:
    - "-text=Hello from Backend"

service:
  type: ClusterIP
  port: 9091

ingress:
  enabled: true
  path: /api
  ingressClassName: nginx
