replicaCount: 2

namespace: frontend

image:
  repository: kemiagbabiaka/react-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: frontend.example.com
  path: /