replicaCount: 1

image:
  repository: kemiagbabiaka/react-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8091

ingress:
  enabled: true
  path: /
  ingressClassName: nginx
